server:
  port: 8080

spring:
  #?????
  datasource:
    url: jdbc:mysql://localhost:3306/onlinejudge?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  # mapper XML ??????
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ???????? ? ????????user_name ? userName?
    map-underscore-to-camel-case: true
    # ?????? SQL ???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # ??
  secret: HammerDoughmiaoazhongziniaiwoyawoainimixuebingchengtianmimi
  # ????????????  ???? 2 ??
  expire: 7200000
  # ????????????
  header: token

file:
  upload:
    path: D:/GitHubProjects/OnlineJudge/oj-upload/avatar
    prefix: /upload/avatar/
